import React, { createContext, useState, useContext } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    // Navbar
    navHome: "Home",
    navAbout: "About Us",
    navJourney: "Career Journey",
    navPortfolio: "Portfolio",
    navServices: "Services",
    navBlog: "Blog",
    navContact: "Contact",
    navGetInTouch: "Get in Touch",
    
    // Home
    homeHello: "Hello, I'm",
    homeName: "Muneeb Farid",
    homeSubtitle1: "A ",
    homeSubtitle2: "Creative AI Engineer",
    homeSubtitle3: " From ",
    homeSubtitle4: "Pakistan",
    homeDescription: "I'm a creative AI Engineer based in Pakistan, and I'm very passionate and dedicated to developing AI-driven solutions.",
    homeAboutMe: "About Me",
    
    // About
    aboutTitle: "About Me",
    aboutSubtitle: "Who I Am",
    aboutDesc: "I specialize in creating clean, robust codebases with excellent design and performance. My stack revolves around modern Javascript and CSS solutions, primarily React, Vite, and Tailwind CSS.",
    aboutHeading: "I'm an AI Engineer",
    aboutSubHeading: "I Can Build Any AI Solution You Need",
    aboutContent: "Hello there! I'm Muneeb Farid, an AI Engineer based in Pakistan, passionate about building cutting-edge artificial intelligence systems, blockchain networks, and cloud integrations. With hands-on experience in LLM development, computer vision, and machine learning, I create intelligent automation pipelines that optimize business performance and scale operations.",
    aboutNameLabel: "NAME:",
    aboutEmailLabel: "EMAIL:",
    aboutPhoneLabel: "PHONE (WHATSAPP):",
    aboutSpecialtyLabel: "SPECIALTY:",
    aboutName: "Muneeb Farid",
    aboutSpecialty: "AI Engineer",
    aboutReadMore: "Read More",
    aboutDownloadCV: "Download CV",
    aboutYearsExp: "Years of Experience",

    // Journey
    journeyTabExp: "Education & Experience",
    journeyTabResearch: "Research Papers",
    journeyTabLead: "Leadership",
    journeyTabCert: "Certificates",

    j1_title: "AI Engineer (Active Job)",
    j1_sub: "Tecveq (UK-based)",
    j1_desc: "Designing and integrating cutting-edge LLM applications, voice assistants, and cloud AI infrastructure to automate business workflows.",
    j1_per: "2025 - Present",

    j2_title: "AI Engineer",
    j2_sub: "Findigit",
    j2_desc: "Built customer support chatbots, product recommendation systems, and computer vision models for object detection and face recognition.",
    j2_per: "2023 - 2024",

    j3_title: "AI-Powered Medical Triage Chatbot for Symptom Assessment...",
    j3_sub: "Muneeb Farid · Research Publication",
    j3_desc: "Developing an AI-powered medical triage system that combines rule-based clinical protocols with machine learning for symptom assessment and risk stratification.",
    j3_per: "2026",

    j4_title: "Design and Evaluation of Multi-Agent AI Systems...",
    j4_sub: "Muneeb Farid · Research Publication",
    j4_desc: "Designed and developed a Multi-Agent System using Large Language Models (LLMs) to enable autonomous task execution and solve real-world industry problems.",
    j4_per: "2025",

    j5_title: "Applying Reinforcement Learning to Decision-Making Problems...",
    j5_sub: "Muneeb Farid · Research Publication",
    j5_desc: "Published BS Final Year Project titled 'A Comparative Study of Classical and Deep Reinforcement Learning Algorithms' focusing on decision-making optimization.",
    j5_per: "2024",

    j6_title: "A new method for image classification based on the fusion...",
    j6_sub: "Muneeb Farid · Research Publication",
    j6_desc: "Developed a novel image classification method utilizing the fusion of multi-level deep learning models to overcome individual model performance limitations.",
    j6_per: "2023",

    j7_title: "Campus Ambassador",
    j7_sub: "Devsinc · Remote",
    j7_desc: "Representing Devsinc on campus, driving student engagement, and connecting peers to internships, events, and hiring opportunities.",
    j7_per: "Feb 2025 - Present",

    j8_title: "Tech Lead & Speaker",
    j8_sub: "GDG · Remote",
    j8_desc: "Led Google Developer Student Clubs as Tech Lead, conducting AI workshops and mentoring students in modern software engineering practices.",
    j8_per: "2023 - 2024",

    j9_title: "AI Expert",
    j9_sub: "DeepLearning.AI",
    j9_desc: "Advanced certification in building applications with Large Language Models and specialized AI architectures.",
    j9_per: "2025",

    j10_title: "AI For Everyone",
    j10_sub: "Coursera",
    j10_desc: "Comprehensive overview of AI applications, strategy, and societal impact.",
    j10_per: "2024",

    j11_title: "Data Science",
    j11_sub: "FreeCodeCamp",
    j11_desc: "Practical data manipulation, analysis, and visualization techniques.",
    j11_per: "2023",

    j12_title: "Bachelor of Computer Science",
    j12_sub: "Comsats University Islamabad Sahiwal Campus, Pakistan",
    j12_desc: "Focused on Artificial Intelligence, Machine Learning, and Advanced Software Engineering.",
    j12_per: "2020 - 2024",

    // Portfolio
    portfolioTitle: "Portfolio",
    portfolioSubtitle: "Recent Work",
    portfolioBannerTitle1: "AI Systems That Drive",
    portfolioBannerTitle2: "Real Business Growth",
    portfolioBannerDesc: "We don't just build models — we engineer end-to-end AI solutions that automate workflows, eliminate bottlenecks, and compound competitive advantage. From LLM-powered chatbots to enterprise vision pipelines, every project is architected to deliver measurable ROI, expand reach, and position your brand as a digital market leader.",
    
    p1_title: "Report News Agent",
    p1_sub: "AI-powered News Reporting Agent",
    p1_desc: "An AI-powered news reporting agent that automatically fetches, summarizes, and delivers daily news updates using LangChain and FastAPI.",

    p2_title: "CLI Coder Agent",
    p2_sub: "Terminal-based AI Assistant",
    p2_desc: "A terminal-based AI assistant designed for developers who want quick, keyboard-first coding help without leaving the command line.",

    p3_title: "Audio Podcast",
    p3_sub: "PDF to Audio AI Tool",
    p3_desc: "Transform your PDFs into engaging audio with our AI-powered podcast tool. Perfect for students, researchers, and busy professionals.",

    p4_title: "Traffic Analysis",
    p4_sub: "Real-Time Traffic Monitoring",
    p4_desc: "A smart system that monitors live traffic data to detect congestion, optimize flow, and improve overall transportation efficiency.",

    p5_title: "Trading Insight",
    p5_sub: "Data Analysis & Insights",
    p5_desc: "A comprehensive data analysis tool built with Jupyter Notebook to extract actionable insights for trading strategies.",

    p6_title: "District Guessing Game",
    p6_sub: "Python GUI Application",
    p6_desc: "An interactive Python GUI guessing game that challenges users to name districts and provides automated reporting on missed entries.",

    // Services
    servicesTitle: "Services",
    servicesSubtitle: "What I Do",
    servicesMyExpertise: "My Expertise",
    servicesWhatIProvide: "What I Provide",
    
    s1_title: "LLM & Generative AI Solutions",
    s1_desc: "Custom ChatGPT-like assistants, automated content generation, and RAG-based document querying.",
    
    s2_title: "AI Workflow Automation",
    s2_desc: "Automating repetitive tasks, CRM data entry, and email outreach with intelligent agents.",
    
    s3_title: "Computer Vision Systems",
    s3_desc: "Object detection, facial recognition, and automated visual inspection for industries.",
    
    s4_title: "Voice AI & Assistants",
    s4_desc: "Interactive voice response (IVR), real-time speech-to-text, and conversational AI callers.",
    
    s5_title: "Data Science & Analytics",
    s5_desc: "Predictive modeling, data visualization, and business intelligence dashboards.",
    
    s6_title: "Full-Stack Web Development",
    s6_desc: "Scalable web applications integrated seamlessly with backend AI models and databases.",

    // Blog
    blogTitle: "Blog",
    blogSubtitle: "Latest Thoughts",
    blogReadArticle: "Read Article",
    blogBack: "Back to Blogs",

    b1_title: "The Future of AI in Web Development",
    b1_date: "July 24, 2026",
    b1_read: "5 min read",
    b1_exc: "Explore how artificial intelligence is reshaping the landscape of web development, from automated coding assistants to intelligent user interfaces...",
    b1_con: "Artificial Intelligence is no longer just a buzzword; it's a fundamental shift in how we approach web development. In recent years, we've seen the rise of AI-powered tools that assist developers in writing code, debugging, and even designing user interfaces. \n\nOne of the most significant impacts of AI is the democratization of development. With tools like GitHub Copilot and ChatGPT, even novice developers can create complex applications. Furthermore, AI is enhancing user experiences by enabling personalized content delivery, intelligent chatbots for customer support, and predictive analytics that anticipate user needs. \n\nAs we look to the future, the integration of AI in web development will only deepen. Developers who embrace these technologies will find themselves at a significant advantage, able to build faster, smarter, and more user-centric applications.",

    b2_title: "Mastering Tailwind CSS for Modern UIs",
    b2_date: "July 18, 2026",
    b2_read: "4 min read",
    b2_exc: "A deep dive into advanced Tailwind CSS techniques for building highly responsive and visually stunning user interfaces with minimal custom CSS...",
    b2_con: "Tailwind CSS has revolutionized the way we style web applications. By providing a utility-first approach, it allows developers to build complex designs directly within their HTML, eliminating the need for bulky CSS files and reducing context switching. \n\nTo truly master Tailwind, one must understand its configuration file (`tailwind.config.js`). This file is the heart of your design system, allowing you to customize colors, spacing, typography, and more to match your brand identity perfectly. \n\nAnother advanced technique is utilizing Tailwind's `@apply` directive to extract common utility patterns into reusable CSS classes. While this shouldn't be overused, it's incredibly helpful for standardizing button styles or form inputs across a large application. Mastering these techniques will significantly speed up your development process and result in cleaner, more maintainable code.",

    b3_title: "Optimizing React Performance in 2026",
    b3_date: "July 10, 2026",
    b3_read: "6 min read",
    b3_exc: "Learn the latest strategies and hooks for keeping your React applications lightning fast, even as they scale in complexity and data volume...",
    b3_con: "As React applications grow in complexity, maintaining optimal performance becomes crucial. In 2026, the strategies for optimizing React have evolved, focusing heavily on concurrent rendering and intelligent state management. \n\nThe `useMemo` and `useCallback` hooks remain fundamental for preventing unnecessary re-renders, but their usage must be deliberate. Overusing them can actually degrade performance due to the overhead of memoization itself. \n\nServer Components, now a standard feature, offer a massive performance boost by rendering components on the server and sending only the necessary HTML to the client, drastically reducing the JavaScript bundle size. Understanding when to use Server Components versus Client Components is the key to building lightning-fast React applications today.",

    // Contact
    contactTitle: "Contact",
    contactSubtitle: "Let's Connect",
    contactDesc: "Want to collaborate, discuss a project, or just say hello? Drop me a message, and let's get started.",
    contactGetInTouch: "Get in Touch",
    contactInfoTitle: "Contact Information",
    contactInfoDesc: "Fill up the form and our Team will get back to you within 24 hours.",
    contactPhone: "Call Us",
    contactEmail: "Email Us",
    contactLocation: "Location",
    contactFormName: "Your Name",
    contactFormEmail: "Your Email",
    contactFormSubject: "Subject",
    contactFormMessage: "Your Message...",
    contactFormSend: "Send Message",

    // Footer
    // Portfolio
    portfolioBannerTitle1: "AI Systems That Drive",
    portfolioBannerTitle2: "Real Business Growth",
    portfolioBannerDesc: "We don't just build models — we engineer end-to-end AI solutions that automate workflows, eliminate bottlenecks, and compound competitive advantage. From LLM-powered chatbots to enterprise vision pipelines, every project is architected to deliver measurable ROI, expand reach, and position your brand as a digital market leader.",
    projectView: "View Project",

    p1_title: "Report News Agent",
    p1_sub: "AI-powered News Reporting Agent",
    p1_desc: "An AI-powered news reporting agent that automatically fetches, summarizes, and delivers daily news updates using LangChain and FastAPI.",

    p2_title: "CLI Coder Agent",
    p2_sub: "Terminal-based AI Assistant",
    p2_desc: "A terminal-based AI assistant designed for developers who want quick, keyboard-first coding help without leaving the command line.",

    p3_title: "Audio Podcast",
    p3_sub: "PDF to Audio AI Tool",
    p3_desc: "Transform your PDFs into engaging audio with our AI-powered podcast tool. Perfect for students, researchers, and busy professionals.",

    p4_title: "Traffic Analysis",
    p4_sub: "Real-Time Traffic Monitoring",
    p4_desc: "A smart system that monitors live traffic data to detect congestion, optimize flow, and improve overall transportation efficiency.",

    p5_title: "Trading Insight",
    p5_sub: "Data Analysis & Insights",
    p5_desc: "A comprehensive data analysis tool built with Jupyter Notebook to extract actionable insights for trading strategies.",

    p6_title: "District Guessing Game",
    p6_sub: "Python GUI Application",
    p6_desc: "An interactive Python GUI guessing game that challenges users to name districts and provides automated reporting on missed entries.",

    footerDesc: "I build robust, scalable AI solutions designed for modern enterprise workflows.",
    footerQuickLinks: "Quick Links",
    footerLegal: "Legal",
    footerPrivacy: "Privacy Policy",
    footerTerms: "Terms of Service",
    footerCookie: "Cookie Policy",
    footerRights: "All rights reserved."
  },
  de: {
    navHome: "Startseite",
    navAbout: "Über Uns",
    navJourney: "Werdegang",
    navPortfolio: "Portfolio",
    navServices: "Dienste",
    navBlog: "Blog",
    navContact: "Kontakt",
    navGetInTouch: "Kontaktieren",
    homeHello: "Hallo, ich bin",
    homeName: "Muneeb Farid",
    homeSubtitle1: "Ein ",
    homeSubtitle2: "Kreativer KI-Ingenieur",
    homeSubtitle3: " Aus ",
    homeSubtitle4: "Pakistan",
    homeDescription: "Ich bin ein kreativer KI-Ingenieur aus Pakistan und widme mich mit großer Leidenschaft der Entwicklung von KI-gesteuerten Lösungen.",
    homeAboutMe: "Über Mich",
    aboutTitle: "Über Mich",
    aboutSubtitle: "Wer Ich Bin",
    aboutDesc: "Ich bin spezialisiert auf die Erstellung sauberer, robuster Codebasen mit hervorragendem Design und Leistung.",
    aboutHeading: "Ich bin ein KI-Ingenieur",
    aboutSubHeading: "Ich Kann Jede KI-Lösung Entwickeln, Die Sie Benötigen",
    aboutContent: "Hallo! Ich bin Muneeb Farid, ein KI-Ingenieur aus Pakistan, leidenschaftlich im Aufbau modernster KI-Systeme.",
    aboutNameLabel: "NAME:",
    aboutEmailLabel: "E-MAIL:",
    aboutPhoneLabel: "TELEFON:",
    aboutSpecialtyLabel: "SPEZIALITÄT:",
    aboutName: "Muneeb Farid",
    aboutSpecialty: "KI-Ingenieur",
    aboutReadMore: "Mehr Lesen",
    aboutDownloadCV: "Lebenslauf Herunterladen",
    aboutYearsExp: "Jahre Erfahrung",
    journeyTabExp: "Bildung & Erfahrung",
    journeyTabResearch: "Forschungsarbeiten",
    journeyTabLead: "Führung",
    journeyTabCert: "Zertifikate",
    j1_title: "KI-Ingenieur (Aktuell)",
    j1_sub: "Tecveq (Großbritannien)",
    j1_desc: "Entwurf und Integration modernster LLM-Anwendungen.",
    j1_per: "2025 - Heute",
    j2_title: "KI-Ingenieur",
    j2_sub: "Findigit",
    j2_desc: "Entwicklung von Kundensupport-Chatbots und Computer-Vision-Modellen.",
    j2_per: "2023 - 2024",
    j3_title: "Medizinischer KI-Chatbot...",
    j3_sub: "Muneeb Farid · Publikation",
    j3_desc: "Entwicklung eines medizinischen KI-Triage-Systems.",
    j3_per: "2026",
    j4_title: "Multi-Agenten-KI-Systeme...",
    j4_sub: "Muneeb Farid · Publikation",
    j4_desc: "Entwicklung eines Multi-Agenten-Systems.",
    j4_per: "2025",
    j5_title: "Reinforcement Learning...",
    j5_sub: "Muneeb Farid · Publikation",
    j5_desc: "Fokus auf Entscheidungsoptimierung.",
    j5_per: "2024",
    j6_title: "Neue Methode zur Bildklassifizierung...",
    j6_sub: "Muneeb Farid · Publikation",
    j6_desc: "Fusion von Deep-Learning-Modellen.",
    j6_per: "2023",
    j7_title: "Campus-Botschafter",
    j7_sub: "Devsinc · Remote",
    j7_desc: "Vertretung von Devsinc auf dem Campus.",
    j7_per: "Feb 2025 - Heute",
    j8_title: "Technischer Leiter",
    j8_sub: "GDG · Remote",
    j8_desc: "Leitung von Google Developer Student Clubs.",
    j8_per: "2023 - 2024",
    j9_title: "KI-Experte",
    j9_sub: "DeepLearning.AI",
    j9_desc: "Erweiterte Zertifizierung für LLM-Anwendungen.",
    j9_per: "2025",
    j10_title: "KI Für Alle",
    j10_sub: "Coursera",
    j10_desc: "Umfassender Überblick über KI.",
    j10_per: "2024",
    j11_title: "Datenwissenschaft",
    j11_sub: "FreeCodeCamp",
    j11_desc: "Praktische Datenanalyse.",
    j11_per: "2023",
    j12_title: "Bachelor in Informatik",
    j12_sub: "Universität Lahore, PK",
    j12_desc: "Fokus auf Künstliche Intelligenz.",
    j12_per: "2020 - 2024",
    portfolioTitle: "Portfolio",
    portfolioSubtitle: "Aktuelle Arbeit",
    portfolioBannerTitle1: "KI-Systeme Die Das",
    portfolioBannerTitle2: "Geschäftswachstum Vorantreiben",
    portfolioBannerDesc: "Wir bauen nicht nur Modelle - wir entwickeln End-to-End KI-Lösungen.",
    p1_title: "Nachrichten-Agent",
    p1_sub: "KI-gesteuerter Agent",
    p1_desc: "Holt täglich Nachrichten-Updates ab.",
    p2_title: "CLI-Coder-Agent",
    p2_sub: "Terminal KI-Assistent",
    p2_desc: "KI-Assistent für Entwickler.",
    p3_title: "Audio-Podcast",
    p3_sub: "PDF zu Audio KI-Tool",
    p3_desc: "Verwandeln Sie PDFs in Audio.",
    p4_title: "Verkehrsanalyse",
    p4_sub: "Echtzeit-Überwachung",
    p4_desc: "Ein intelligentes System zur Überwachung von Verkehrsdaten.",
    p5_title: "Handels-Erkenntnisse",
    p5_sub: "Datenanalyse",
    p5_desc: "Ein Tool zur Datenanalyse.",
    p6_title: "Bezirks-Rate-Spiel",
    p6_sub: "Python GUI App",
    p6_desc: "Ein interaktives Python-Spiel.",
    servicesTitle: "Dienste",
    servicesSubtitle: "Was Ich Tue",
    servicesMyExpertise: "Meine Expertise",
    servicesWhatIProvide: "Was Ich Biete",
    s1_title: "LLM & Generative KI",
    s1_desc: "Maßgeschneiderte ChatGPT-ähnliche Assistenten.",
    s2_title: "KI-Workflow-Automatisierung",
    s2_desc: "Automatisierung von sich wiederholenden Aufgaben.",
    s3_title: "Computer-Vision-Systeme",
    s3_desc: "Objekterkennung und Gesichtserkennung.",
    s4_title: "Sprach-KI",
    s4_desc: "Echtzeit-Sprache-zu-Text.",
    s5_title: "Datenanalyse",
    s5_desc: "Prädiktive Modellierung und Dashboards.",
    s6_title: "Webentwicklung",
    s6_desc: "Skalierbare Webanwendungen.",
    blogTitle: "Blog",
    blogSubtitle: "Aktuelle Gedanken",
    blogReadArticle: "Artikel Lesen",
    blogBack: "Zurück zu Blogs",
    b1_title: "Die Zukunft der KI in der Webentwicklung",
    b1_date: "24. Juli 2026",
    b1_read: "5 Min Lesezeit",
    b1_exc: "Erfahren Sie, wie KI die Webentwicklung neu gestaltet...",
    b1_con: "Künstliche Intelligenz ist nicht mehr nur ein Schlagwort...",
    b2_title: "Tailwind CSS für Moderne UIs",
    b2_date: "18. Juli 2026",
    b2_read: "4 Min Lesezeit",
    b2_exc: "Ein tiefer Einblick in fortgeschrittene Techniken...",
    b2_con: "Tailwind CSS hat die Art und Weise, wie wir Webanwendungen stylen, revolutioniert...",
    b3_title: "Optimierung der React-Performance",
    b3_date: "10. Juli 2026",
    b3_read: "6 Min Lesezeit",
    b3_exc: "Lernen Sie die neuesten Strategien für React...",
    b3_con: "Mit zunehmender Komplexität von React-Anwendungen...",
    contactTitle: "Kontakt",
    contactSubtitle: "Verbinden Wir Uns",
    contactDesc: "Möchten Sie zusammenarbeiten?",
    contactGetInTouch: "Kontaktieren",
    contactInfoTitle: "Kontaktinformationen",
    contactInfoDesc: "Füllen Sie das Formular aus.",
    contactPhone: "Rufen Sie an",
    contactEmail: "E-Mail",
    contactLocation: "Ort",
    contactFormName: "Ihr Name",
    contactFormEmail: "Ihre E-Mail",
    contactFormSubject: "Betreff",
    contactFormMessage: "Ihre Nachricht...",
    contactFormSend: "Nachricht Senden",
    footerDesc: "Ich baue robuste, skalierbare KI-Lösungen, die für moderne Unternehmens-Workflows entwickelt wurden.",
    footerQuickLinks: "Schnelllinks",
    footerLegal: "Rechtliches",
    footerPrivacy: "Datenschutz",
    footerTerms: "Nutzungsbedingungen",
    footerCookie: "Cookie-Richtlinie",
    footerRights: "Alle Rechte vorbehalten."
  },
  fr: {
    navHome: "Accueil",
    navAbout: "À Propos",
    navJourney: "Parcours",
    navPortfolio: "Portfolio",
    navServices: "Services",
    navBlog: "Blog",
    navContact: "Contact",
    navGetInTouch: "Contactez-moi",
    homeHello: "Bonjour, je suis",
    homeName: "Muneeb Farid",
    homeSubtitle1: "Un ",
    homeSubtitle2: "Ingénieur IA Créatif",
    homeSubtitle3: " Du ",
    homeSubtitle4: "Pakistan",
    homeDescription: "Je suis un ingénieur IA créatif basé au Pakistan, passionné par le développement de solutions IA.",
    homeAboutMe: "À Propos De Moi",
    aboutTitle: "À Propos",
    aboutSubtitle: "Qui Je Suis",
    aboutDesc: "Je crée des bases de code robustes avec un excellent design.",
    aboutHeading: "Je Suis Ingénieur IA",
    aboutSubHeading: "Je Peux Créer Toute Solution IA Dont Vous Avez Besoin",
    aboutContent: "Bonjour! Je suis Muneeb Farid, un ingénieur IA du Pakistan.",
    aboutNameLabel: "NOM:",
    aboutEmailLabel: "EMAIL:",
    aboutPhoneLabel: "TÉLÉPHONE:",
    aboutSpecialtyLabel: "SPÉCIALITÉ:",
    aboutName: "Muneeb Farid",
    aboutSpecialty: "Ingénieur IA",
    aboutReadMore: "Lire La Suite",
    aboutDownloadCV: "Télécharger CV",
    aboutYearsExp: "Années D'expérience",
    journeyTabExp: "Éducation & Expérience",
    journeyTabResearch: "Publications",
    journeyTabLead: "Leadership",
    journeyTabCert: "Certificats",
    j1_title: "Ingénieur IA (Actuel)",
    j1_sub: "Tecveq (Royaume-Uni)",
    j1_desc: "Conception et intégration d'applications LLM.",
    j1_per: "2025 - Présent",
    j2_title: "Ingénieur IA",
    j2_sub: "Findigit",
    j2_desc: "Développement de chatbots et modèles de vision.",
    j2_per: "2023 - 2024",
    j3_title: "Chatbot de Triage Médical...",
    j3_sub: "Muneeb Farid · Publication",
    j3_desc: "Développement d'un système de triage IA.",
    j3_per: "2026",
    j4_title: "Systèmes IA Multi-Agents...",
    j4_sub: "Muneeb Farid · Publication",
    j4_desc: "Conception d'un système multi-agents.",
    j4_per: "2025",
    j5_title: "Apprentissage par Renforcement...",
    j5_sub: "Muneeb Farid · Publication",
    j5_desc: "Optimisation de la prise de décision.",
    j5_per: "2024",
    j6_title: "Nouvelle méthode de classification...",
    j6_sub: "Muneeb Farid · Publication",
    j6_desc: "Fusion de modèles de deep learning.",
    j6_per: "2023",
    j7_title: "Ambassadeur du Campus",
    j7_sub: "Devsinc · À distance",
    j7_desc: "Représentation de Devsinc sur le campus.",
    j7_per: "Fév 2025 - Présent",
    j8_title: "Lead Technique",
    j8_sub: "GDG · À distance",
    j8_desc: "Direction des Google Developer Student Clubs.",
    j8_per: "2023 - 2024",
    j9_title: "Expert IA",
    j9_sub: "DeepLearning.AI",
    j9_desc: "Certification avancée pour les applications LLM.",
    j9_per: "2025",
    j10_title: "L'IA Pour Tous",
    j10_sub: "Coursera",
    j10_desc: "Aperçu complet de l'IA.",
    j10_per: "2024",
    j11_title: "Science des Données",
    j11_sub: "FreeCodeCamp",
    j11_desc: "Analyse de données pratique.",
    j11_per: "2023",
    j12_title: "Licence en Informatique",
    j12_sub: "Université de Lahore, PK",
    j12_desc: "Axé sur l'IA et l'apprentissage automatique.",
    j12_per: "2020 - 2024",
    portfolioTitle: "Portfolio",
    portfolioSubtitle: "Travaux Récents",
    portfolioBannerTitle1: "Des systèmes d'IA qui stimulent",
    portfolioBannerTitle2: "Une vraie croissance",
    portfolioBannerDesc: "Nous ne construisons pas seulement des modèles — nous concevons des solutions d'IA de bout en bout qui automatisent les flux de travail, éliminent les goulots d'étranglement et renforcent l'avantage concurrentiel. Des chatbots propulsés par les LLM aux pipelines de vision d'entreprise, chaque projet est architecturé pour offrir un retour sur investissement mesurable, étendre la portée et positionner votre marque comme un leader numérique.",
    projectView: "Voir le Projet",
    p1_title: "Agent de Presse",
    p1_sub: "Agent de reportage d'actualités alimenté par l'IA",
    p1_desc: "Un agent de presse qui récupère, résume et fournit automatiquement des mises à jour quotidiennes en utilisant LangChain et FastAPI.",
    p2_title: "Agent Codeur CLI",
    p2_sub: "Assistant IA basé sur terminal",
    p2_desc: "Un assistant IA conçu pour les développeurs qui souhaitent une aide au codage rapide au clavier, sans quitter la ligne de commande.",
    p3_title: "Podcast Audio",
    p3_sub: "Outil IA de PDF à Audio",
    p3_desc: "Transformez vos PDF en audio captivant avec notre outil de podcast IA. Parfait pour les étudiants, chercheurs et professionnels occupés.",
    p4_title: "Analyse du Trafic",
    p4_sub: "Surveillance du trafic en temps réel",
    p4_desc: "Un système intelligent qui surveille les données de trafic en direct pour détecter la congestion, optimiser le flux et améliorer l'efficacité des transports.",
    p5_title: "Aperçu du Trading",
    p5_sub: "Analyse de données et aperçus",
    p5_desc: "Un outil complet d'analyse de données créé avec Jupyter Notebook pour extraire des informations exploitables pour les stratégies de trading.",
    p6_title: "Jeu des Districts",
    p6_sub: "Application GUI Python",
    p6_desc: "Un jeu interactif en GUI Python qui met les utilisateurs au défi de nommer des districts et fournit des rapports automatisés sur les entrées manquées.",
    servicesTitle: "Services",
    servicesSubtitle: "Ce Que Je Fais",
    servicesMyExpertise: "Mon Expertise",
    servicesWhatIProvide: "Ce Que Je Fournis",
    s1_title: "Solutions LLM",
    s1_desc: "Assistants de type ChatGPT personnalisés.",
    s2_title: "Automatisation",
    s2_desc: "Automatisation des tâches répétitives.",
    s3_title: "Vision par Ordinateur",
    s3_desc: "Détection d'objets et reconnaissance faciale.",
    s4_title: "IA Vocale",
    s4_desc: "Conversion de la parole en texte en temps réel.",
    s5_title: "Science des Données",
    s5_desc: "Modélisation prédictive et tableaux de bord.",
    s6_title: "Développement Web",
    s6_desc: "Applications web évolutives.",
    blogTitle: "Blog",
    blogSubtitle: "Dernières Pensées",
    blogReadArticle: "Lire l'Article",
    blogBack: "Retour aux Blogs",
    b1_title: "L'Avenir de l'IA dans le Web",
    b1_date: "24 Juillet 2026",
    b1_read: "5 min de lecture",
    b1_exc: "Explorez comment l'IA remodele le développement web...",
    b1_con: "L'IA n'est plus seulement un mot à la mode...",
    b2_title: "Maîtriser Tailwind CSS",
    b2_date: "18 Juillet 2026",
    b2_read: "4 min de lecture",
    b2_exc: "Une plongée profonde dans les techniques avancées...",
    b2_con: "Tailwind CSS a révolutionné la façon dont nous concevons...",
    b3_title: "Optimisation de React",
    b3_date: "10 Juillet 2026",
    b3_read: "6 min de lecture",
    b3_exc: "Apprenez les dernières stratégies pour React...",
    b3_con: "À mesure que les applications grandissent en complexité...",
    contactTitle: "Contact",
    contactSubtitle: "Connectons-Nous",
    contactDesc: "Vous voulez collaborer?",
    contactGetInTouch: "Contactez-moi",
    contactInfoTitle: "Coordonnées",
    contactInfoDesc: "Remplissez le formulaire.",
    contactPhone: "Appelez-nous",
    contactEmail: "Envoyez-nous un Email",
    contactLocation: "Emplacement",
    contactFormName: "Votre Nom",
    contactFormEmail: "Votre Email",
    contactFormSubject: "Sujet",
    contactFormMessage: "Votre Message...",
    contactFormSend: "Envoyer le Message",
    footerDesc: "Je construis des solutions d'IA robustes et évolutives conçues pour les flux de travail des entreprises modernes.",
    footerLegal: "Mentions Légales",
    footerPrivacy: "Politique de Confidentialité",
    footerTerms: "Conditions d'Utilisation",
    footerCookie: "Politique de Cookies",
    footerRights: "Tous droits réservés."
  },
  zh: {
    navHome: "首页",
    navAbout: "关于我们",
    navJourney: "职业历程",
    navPortfolio: "作品集",
    navServices: "服务项目",
    navBlog: "博客",
    navContact: "联系我",
    navGetInTouch: "取得联系",
    homeHello: "你好，我是",
    homeName: "Muneeb Farid",
    homeSubtitle1: "一位来自",
    homeSubtitle2: "巴基斯坦",
    homeSubtitle3: "的",
    homeSubtitle4: "创意人工智能工程师",
    homeDescription: "我是巴基斯坦的创意人工智能工程师，致力于开发人工智能驱动的解决方案。",
    homeAboutMe: "关于我",
    aboutTitle: "关于我",
    aboutSubtitle: "我是谁",
    aboutDesc: "我专注于创建清洁、健壮的代码库。",
    aboutHeading: "我是一名 AI 工程师",
    aboutSubHeading: "我可以构建您需要的任何 AI 解决方案",
    aboutContent: "你好！我是 Muneeb Farid，来自巴基斯坦的 AI 工程师。",
    aboutNameLabel: "姓名:",
    aboutEmailLabel: "电子邮件:",
    aboutPhoneLabel: "电话:",
    aboutSpecialtyLabel: "专业:",
    aboutName: "Muneeb Farid",
    aboutSpecialty: "AI 工程师",
    aboutReadMore: "阅读更多",
    aboutDownloadCV: "下载简历",
    aboutYearsExp: "年经验",
    journeyTabExp: "教育与经验",
    journeyTabResearch: "研究论文",
    journeyTabLead: "领导力",
    journeyTabCert: "证书",
    j1_title: "AI 工程师 (现任)",
    j1_sub: "Tecveq (英国)",
    j1_desc: "设计和集成前沿的 LLM 应用程序。",
    j1_per: "2025 - 至今",
    j2_title: "AI 工程师",
    j2_sub: "Findigit",
    j2_desc: "构建客户支持聊天机器人。",
    j2_per: "2023 - 2024",
    j3_title: "医疗分诊 AI 聊天机器人...",
    j3_sub: "Muneeb Farid · 研究论文",
    j3_desc: "开发 AI 驱动的医疗分诊系统。",
    j3_per: "2026",
    j4_title: "多代理 AI 系统...",
    j4_sub: "Muneeb Farid · 研究论文",
    j4_desc: "设计并开发了多代理系统。",
    j4_per: "2025",
    j5_title: "强化学习...",
    j5_sub: "Muneeb Farid · 研究论文",
    j5_desc: "专注于决策优化。",
    j5_per: "2024",
    j6_title: "基于多级深度学习融合的新图像分类方法...",
    j6_sub: "Muneeb Farid · 研究论文",
    j6_desc: "利用深度学习模型融合。",
    j6_per: "2023",
    j7_title: "校园大使",
    j7_sub: "Devsinc · 远程",
    j7_desc: "代表校园的 Devsinc。",
    j7_per: "2025年2月 - 至今",
    j8_title: "技术负责人",
    j8_sub: "GDG · 远程",
    j8_desc: "领导谷歌开发者学生俱乐部。",
    j8_per: "2023 - 2024",
    j9_title: "AI 专家",
    j9_sub: "DeepLearning.AI",
    j9_desc: "大型语言模型应用高级认证。",
    j9_per: "2025",
    j10_title: "全民 AI",
    j10_sub: "Coursera",
    j10_desc: "人工智能应用全面概述。",
    j10_per: "2024",
    j11_title: "数据科学",
    j11_sub: "FreeCodeCamp",
    j11_desc: "实用数据分析。",
    j11_per: "2023",
    j12_title: "计算机科学学士",
    j12_sub: "拉合尔大学",
    j12_desc: "专注于人工智能和机器学习。",
    j12_per: "2020 - 2024",
    portfolioTitle: "作品集",
    portfolioSubtitle: "近期工作",
    portfolioBannerTitle1: "驱动成长的",
    portfolioBannerTitle2: "真正商业人工智能系统",
    portfolioBannerDesc: "我们不仅构建模型，我们还设计端到端的人工智能解决方案，实现工作流程自动化，消除瓶颈并增强竞争优势。从LLM驱动的聊天机器人到企业视觉系统，每个项目旨在提供可衡量的投资回报率，扩大影响力，并将您的品牌定位为数字市场领导者。",
    projectView: "查看项目",
    p1_title: "新闻报道代理",
    p1_sub: "AI驱动的新闻代理",
    p1_desc: "一个利用LangChain和FastAPI自动获取、总结和发布每日新闻更新的AI新闻报道代理。",
    p2_title: "CLI 编码代理",
    p2_sub: "基于终端的AI助手",
    p2_desc: "专为希望在不离开命令行的前提下获得快速键盘优先编码帮助的开发人员设计的终端AI助手。",
    p3_title: "音频播客",
    p3_sub: "PDF转音频AI工具",
    p3_desc: "使用我们的人工智能播客工具将您的PDF转换为引人入胜的音频。非常适合学生、研究人员和忙碌的专业人士。",
    p4_title: "交通分析",
    p4_sub: "实时交通监控",
    p4_desc: "一个智能系统监控实时交通数据，以检测拥堵，优化流量并提高整体运输效率。",
    p5_title: "交易洞察",
    p5_sub: "数据分析和洞察",
    p5_desc: "使用Jupyter Notebook构建的综合数据分析工具，提取交易策略的可操作见解。",
    p6_title: "区域猜谜游戏",
    p6_sub: "Python GUI应用程序",
    p6_desc: "一个交互式Python GUI猜谜游戏，挑战用户命名区域并提供错误条目的自动报告。",
    servicesTitle: "服务项目",
    servicesSubtitle: "我做什么",
    servicesMyExpertise: "我的专长",
    servicesWhatIProvide: "我提供什么",
    s1_title: "LLM 解决方案",
    s1_desc: "定制的 ChatGPT 助手。",
    s2_title: "AI 工作流自动化",
    s2_desc: "自动化重复任务。",
    s3_title: "计算机视觉",
    s3_desc: "对象检测和面部识别。",
    s4_title: "语音 AI",
    s4_desc: "实时语音转文本。",
    s5_title: "数据科学",
    s5_desc: "预测建模和仪表板。",
    s6_title: "Web 开发",
    s6_desc: "可扩展的 Web 应用程序。",
    blogTitle: "博客",
    blogSubtitle: "最新想法",
    blogReadArticle: "阅读文章",
    blogBack: "返回博客",
    b1_title: "AI 在 Web 开发中的未来",
    b1_date: "2026年7月24日",
    b1_read: "5 分钟阅读",
    b1_exc: "探索人工智能如何重塑 Web 开发...",
    b1_con: "人工智能不再只是一个流行词...",
    b2_title: "掌握 Tailwind CSS",
    b2_date: "2026年7月18日",
    b2_read: "4 分钟阅读",
    b2_exc: "深入探讨高级 Tailwind CSS 技术...",
    b2_con: "Tailwind CSS 彻底改变了我们的样式设计...",
    b3_title: "优化 React 性能",
    b3_date: "2026年7月10日",
    b3_read: "6 分钟阅读",
    b3_exc: "了解最新的 React 策略...",
    b3_con: "随着 React 应用程序变得复杂...",
    contactTitle: "联系我",
    contactSubtitle: "让我们联系",
    contactDesc: "想合作吗？",
    contactGetInTouch: "取得联系",
    contactInfoTitle: "联系信息",
    contactInfoDesc: "填写表格。",
    contactPhone: "致电我们",
    contactEmail: "发送电子邮件",
    contactLocation: "位置",
    contactFormName: "您的名字",
    contactFormEmail: "您的电子邮件",
    contactFormSubject: "主题",
    contactFormMessage: "您的留言...",
    contactFormSend: "发送信息",
    footerDesc: "我为现代企业工作流程构建稳健、可扩展的AI解决方案。",
    footerQuickLinks: "快速链接",
    footerLegal: "法律",
    footerPrivacy: "隐私政策",
    footerTerms: "服务条款",
    footerCookie: "Cookie 政策",
    footerRights: "版权所有."
  },
  ar: {
    navHome: "الرئيسية",
    navAbout: "من نحن",
    navJourney: "المسار المهني",
    navPortfolio: "المعرض",
    navServices: "الخدمات",
    navBlog: "المدونة",
    navContact: "اتصل بنا",
    navGetInTouch: "تواصل معي",
    homeHello: "مرحباً، أنا",
    homeName: "منيب فريد",
    homeSubtitle1: "مهندس ",
    homeSubtitle2: "ذكاء اصطناعي مبدع",
    homeSubtitle3: " من ",
    homeSubtitle4: "باكستان",
    homeDescription: "أنا مهندس ذكاء اصطناعي مبدع في باكستان.",
    homeAboutMe: "معلومات عني",
    aboutTitle: "نبذة عني",
    aboutSubtitle: "من أكون",
    aboutDesc: "أنا متخصص في إنشاء قواعد أكواد قوية ونظيفة.",
    aboutHeading: "أنا مهندس ذكاء اصطناعي",
    aboutSubHeading: "يمكنني بناء أي حل ذكاء اصطناعي تحتاجه",
    aboutContent: "مرحباً! أنا منيب فريد، مهندس ذكاء اصطناعي في باكستان.",
    aboutNameLabel: "الاسم:",
    aboutEmailLabel: "البريد الإلكتروني:",
    aboutPhoneLabel: "رقم الهاتف:",
    aboutSpecialtyLabel: "التخصص:",
    aboutName: "منيب فريد",
    aboutSpecialty: "مهندس ذكاء اصطناعي",
    aboutReadMore: "اقرأ المزيد",
    aboutDownloadCV: "تحميل السيرة الذاتية",
    aboutYearsExp: "سنوات من الخبرة",
    journeyTabExp: "التعليم والخبرة",
    journeyTabResearch: "الأوراق البحثية",
    journeyTabLead: "القيادة",
    journeyTabCert: "الشهادات",
    j1_title: "مهندس ذكاء اصطناعي (الحالي)",
    j1_sub: "تيكفيك (المملكة المتحدة)",
    j1_desc: "تصميم ودمج تطبيقات LLM الحديثة.",
    j1_per: "2025 - الحاضر",
    j2_title: "مهندس ذكاء اصطناعي",
    j2_sub: "فاين ديجيت",
    j2_desc: "بناء روبوتات محادثة لدعم العملاء.",
    j2_per: "2023 - 2024",
    j3_title: "روبوت الدردشة للفرز الطبي...",
    j3_sub: "منيب فريد · نشر بحثي",
    j3_desc: "تطوير نظام فرز طبي مدعوم بالذكاء الاصطناعي.",
    j3_per: "2026",
    j4_title: "أنظمة الذكاء الاصطناعي متعددة الوكلاء...",
    j4_sub: "منيب فريد · نشر بحثي",
    j4_desc: "تصميم نظام متعدد الوكلاء.",
    j4_per: "2025",
    j5_title: "التعلم المعزز...",
    j5_sub: "منيب فريد · نشر بحثي",
    j5_desc: "التركيز على تحسين اتخاذ القرار.",
    j5_per: "2024",
    j6_title: "طريقة جديدة لتصنيف الصور...",
    j6_sub: "منيب فريد · نشر بحثي",
    j6_desc: "دمج نماذج التعلم العميق.",
    j6_per: "2023",
    j7_title: "سفير الحرم الجامعي",
    j7_sub: "Devsinc · عن بعد",
    j7_desc: "تمثيل الشركة في الحرم الجامعي.",
    j7_per: "فبراير 2025 - الحاضر",
    j8_title: "القائد التقني",
    j8_sub: "GDG · عن بعد",
    j8_desc: "قيادة نوادي جوجل للطلاب.",
    j8_per: "2023 - 2024",
    j9_title: "خبير الذكاء الاصطناعي",
    j9_sub: "DeepLearning.AI",
    j9_desc: "شهادة متقدمة لتطبيقات الذكاء الاصطناعي.",
    j9_per: "2025",
    j10_title: "الذكاء الاصطناعي للجميع",
    j10_sub: "Coursera",
    j10_desc: "نظرة شاملة.",
    j10_per: "2024",
    j11_title: "علم البيانات",
    j11_sub: "FreeCodeCamp",
    j11_desc: "تحليل البيانات العملية.",
    j11_per: "2023",
    j12_title: "بكالوريوس علوم الحاسوب",
    j12_sub: "جامعة لاهور",
    j12_desc: "التركيز على الذكاء الاصطناعي.",
    j12_per: "2020 - 2024",
    portfolioTitle: "المعرض",
    portfolioSubtitle: "أحدث الأعمال",
    portfolioBannerTitle1: "أنظمة الذكاء الاصطناعي التي تدفع",
    portfolioBannerTitle2: "النمو الحقيقي للأعمال",
    portfolioBannerDesc: "نحن لا نبني النماذج فحسب — بل نبتكر حلول ذكاء اصطناعي شاملة تعمل على أتمتة تدفقات العمل والقضاء على الاختناقات ومضاعفة الميزة التنافسية. من روبوتات المحادثة المدعومة بنماذج اللغة الكبيرة إلى مسارات الرؤية المؤسسية، يتم تصميم كل مشروع لتقديم عائد استثمار قابل للقياس، وتوسيع نطاق الوصول، وترسيخ علامتك التجارية كشركة رائدة في السوق الرقمية.",
    projectView: "عرض المشروع",
    p1_title: "وكيل تقارير الأخبار",
    p1_sub: "وكيل إخباري مدعوم بالذكاء الاصطناعي",
    p1_desc: "وكيل إخباري يعمل بالذكاء الاصطناعي يقوم تلقائيًا بجلب ملخصات وتحديثات الأخبار اليومية وتسليمها باستخدام LangChain و FastAPI.",
    p2_title: "وكيل كود CLI",
    p2_sub: "مساعد ذكاء اصطناعي في الطرفية",
    p2_desc: "مساعد ذكاء اصطناعي مبني على الطرفية مصمم للمطورين الذين يرغبون في مساعدة برمجية سريعة عبر لوحة المفاتيح دون مغادرة سطر الأوامر.",
    p3_title: "بودكاست صوتي",
    p3_sub: "أداة ذكاء اصطناعي لتحويل PDF إلى صوت",
    p3_desc: "قم بتحويل ملفات PDF الخاصة بك إلى ملفات صوتية جذابة مع أداة البودكاست المدعومة بالذكاء الاصطناعي. مثالي للطلاب والباحثين والمهنيين المشغولين.",
    p4_title: "تحليل حركة المرور",
    p4_sub: "مراقبة حركة المرور في الوقت الفعلي",
    p4_desc: "نظام ذكي يراقب بيانات حركة المرور الحية لاكتشاف الازدحام، وتحسين التدفق، وتحسين كفاءة النقل بشكل عام.",
    p5_title: "رؤية التداول",
    p5_sub: "تحليل البيانات والرؤى",
    p5_desc: "أداة تحليل بيانات شاملة مبنية باستخدام Jupyter Notebook لاستخراج رؤى قابلة للتنفيذ لاستراتيجيات التداول.",
    p6_title: "لعبة تخمين المناطق",
    p6_sub: "تطبيق Python GUI",
    p6_desc: "لعبة تخمين تفاعلية بواجهة مستخدم رسومية في Python تتحدى المستخدمين لتسمية المناطق وتوفر تقارير تلقائية عن الإدخالات المفقودة.",
    servicesTitle: "الخدمات",
    servicesSubtitle: "ماذا أقدم",
    servicesMyExpertise: "خبرتي",
    servicesWhatIProvide: "ما أقدمه",
    s1_title: "حلول الذكاء الاصطناعي",
    s1_desc: "مساعدين مخصصين.",
    s2_title: "أتمتة سير العمل",
    s2_desc: "أتمتة المهام المتكررة.",
    s3_title: "رؤية الكمبيوتر",
    s3_desc: "التعرف على الوجوه والأشياء.",
    s4_title: "الذكاء الاصطناعي الصوتي",
    s4_desc: "تحويل الكلام إلى نص.",
    s5_title: "علم البيانات",
    s5_desc: "تحليل البيانات واللوحات.",
    s6_title: "تطوير الويب",
    s6_desc: "تطبيقات الويب.",
    blogTitle: "المدونة",
    blogSubtitle: "آخر الأفكار",
    blogReadArticle: "اقرأ المقال",
    blogBack: "العودة إلى المدونات",
    b1_title: "مستقبل الذكاء الاصطناعي في الويب",
    b1_date: "24 يوليو 2026",
    b1_read: "5 دقائق قراءة",
    b1_exc: "اكتشف كيف يغير الذكاء الاصطناعي الويب...",
    b1_con: "الذكاء الاصطناعي لم يعد مجرد كلمة طنانة...",
    b2_title: "إتقان Tailwind CSS",
    b2_date: "18 يوليو 2026",
    b2_read: "4 دقائق قراءة",
    b2_exc: "غوص عميق في التقنيات المتقدمة...",
    b2_con: "أحدثت Tailwind CSS ثورة في التصميم...",
    b3_title: "تحسين أداء React",
    b3_date: "10 يوليو 2026",
    b3_read: "6 دقائق قراءة",
    b3_exc: "تعلم أحدث الاستراتيجيات...",
    b3_con: "مع زيادة تعقيد التطبيقات...",
    contactTitle: "اتصل بي",
    contactSubtitle: "دعنا نتواصل",
    contactDesc: "هل تريد التعاون؟",
    contactGetInTouch: "تواصل معي",
    contactInfoTitle: "معلومات الاتصال",
    contactInfoDesc: "املأ النموذج.",
    contactPhone: "اتصل بنا",
    contactEmail: "أرسل بريد إلكتروني",
    contactLocation: "الموقع",
    contactFormName: "اسمك",
    contactFormEmail: "بريدك الإلكتروني",
    contactFormSubject: "الموضوع",
    contactFormMessage: "رسالتك...",
    contactFormSend: "إرسال الرسالة",
    footerDesc: "أقوم ببناء حلول ذكاء اصطناعي قوية وقابلة للتطوير مصممة لسير عمل الشركات الحديثة.",
    footerQuickLinks: "روابط سريعة",
    footerLegal: "قانوني",
    footerPrivacy: "سياسة الخصوصية",
    footerTerms: "شروط الخدمة",
    footerCookie: "سياسة ملفات الارتباط",
    footerRights: "جميع الحقوق محفوظة."
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');

  const t = (key) => {
    return translations[language][key] || key;
  };

  const isRTL = language === 'ar';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      <div dir={isRTL ? 'rtl' : 'ltr'} className={isRTL ? 'font-sans text-right' : 'font-sans'}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
